### ISSUE TITLE
求问大佬运行报错

### ISSUE THREAD

**Issue by qaw944416252** [kekeqy/ke-rtsp#14]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-loglevel',
    'quiet',
    '-i',
    'rtsp://admin:admin888@192.168.1.64:554/h264/ch1/main/av_stream',
    '-an',
    '-c:v',
    'copy',
    '-f',
    'mp4',
    '-movflags',
    '+frag_keyframe+empty_moov+default_base_moof',
    'pipe:1'
  ]
}

**Comment by kekeqy** [comment]
#9
